apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: search
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: ${REGISTRY}/search:${VERSION}
        ports:
        - containerPort: 5000
        env:
        - name: SEARCH_DB
          valueFrom:
            secretKeyRef:
              name: ${SEARCH_DB_SECRET}
              key: searchDatabase
      imagePullSecrets:
      - name: ${REGISTRY_SECRET}
---
apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: ${NAMESPACE}
spec:
  ports:
  - name: default
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: search
  type: NodePort 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: search
  namespace: ${NAMESPACE}
spec:
  rules:
  - host: search.${HOST}
    http:
      paths:
      - path: /
        backend:
          serviceName: search
          servicePort: 5000
      - path: /search
        backend:
          serviceName: search
          servicePort: 5000
  - http:
      paths:
      - path: /
        backend:
          serviceName: search
          servicePort: 5000
      - path: /search
        backend:
          serviceName: search
          servicePort: 5000
