run:
	@echo "=============Running system locally with docker compose============="
	docker-compose -f ./dev/.docker-compose.yml up

clean:
	@echo "=============Removing local databases and stopping docker compose============="
	docker-compose -f ./dev/.docker-compose.yml down