apiVersion: v1
kind: Service
metadata:
  name: grafananode
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  type: NodePort 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  backend:
    serviceName: grafananode
    servicePort: 3000
