apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: search
        image: "{{ .Values.registry }}/ui:{{ .Values.version }}"
        ports:
        - containerPort: 5000
        env:
        - name: SEARCH_ENDPOINT
          value: http://search:5000
        - name: AD_ENDPOINT
          value: http://ad:5000
      imagePullSecrets:
      - name: registry
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: default
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: ui
  type: NodePort 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: "ui.{{ .Values.host }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: ui
          servicePort: 5000
      - path: /search
        backend:
          serviceName: ui
          servicePort: 5000
  - http:
      paths:
      - path: /
        backend:
          serviceName: ui
          servicePort: 5000
      - path: /search
        backend:
          serviceName: ui
          servicePort: 5000
